### ISSUE TITLE
Issues with run dev

### ISSUE THREAD

**Issue by mmmintdesign** [the-dataface/figma-plugin-svelte-vite#14]
Running npm run dev give an error:
`node_modules\concurrently\dist\bin\concurrently.js:224
    prefixColors: args.prefixColors.split(','),`

A quick search said ` prefixColors: args.prefixColors.split(',')` needs to be ` prefixColors: args.prefixColors.toString().split(',')` instead.

After changing. npm run dev gives vite error, vite is not recognized...:
![image](https://github.com/user-attachments/assets/695f2db6-f7af-4eb9-a4b6-50d2f8e6d97f)

**Comment by mmmintdesign** [comment]
I assume it's something with concurrently.js.
So maybe instead of making one script to run both UI and plugin, add 2 scripts dev:UI and dev:plugin, and run them in 2 terminals?

**Comment by sawyerclick** [comment]
Thanks for opening! I'll take a look this week.

**Comment by sawyerclick** [comment]
I'm unable to reproduce this. Could you confirm what version of node you are using and if you had updated and other dependencies?

Other than that, I added the separate scripts as a part of [5d4b6eb](https://github.com/the-dataface/figma-plugin-svelte-vite/commit/5d4b6ebf7d909f1ccffb08a62af378367bc58648)

**Comment by mmmintdesign** [comment]
It seems like ther problem was with the single apostrophes.
Created pull request #15
